// Generated by CoffeeScript 1.3.3
(function() {
  var $;

  $ = this.oye.$;

  this.oye.fetchMethods = {
    "siteName": "京东",
    "goodsName": function() {
      var _ref;
      return typeof pageConfig !== "undefined" && pageConfig !== null ? (_ref = pageConfig.product) != null ? _ref.name : void 0 : void 0;
    },
    "price": function() {
      var _ref;
      return typeof pageConfig !== "undefined" && pageConfig !== null ? (_ref = pageConfig.product) != null ? _ref.price : void 0 : void 0;
    },
    "prop": function() {
      var el;
      el = $("#choose-result .dd").clone();
      el.find("em").remove();
      return el.text();
    },
    "img": function() {
      return $("#spec-n1 img").attr("src");
    }
  };

}).call(this);
